//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSToDatabaseSoap")]
    public interface WSToDatabaseSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        BetWeb.ServiceReference1.LoginResponse Login(BetWeb.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.LoginResponse> LoginAsync(BetWeb.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewUser", ReplyAction="*")]
        BetWeb.ServiceReference1.AddNewUserResponse AddNewUser(BetWeb.ServiceReference1.AddNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddNewUserResponse> AddNewUserAsync(BetWeb.ServiceReference1.AddNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        BetWeb.ServiceReference1.DeleteUserResponse DeleteUser(BetWeb.ServiceReference1.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.DeleteUserResponse> DeleteUserAsync(BetWeb.ServiceReference1.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        BetWeb.ServiceReference1.GetUsersResponse GetUsers(BetWeb.ServiceReference1.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUsersResponse> GetUsersAsync(BetWeb.ServiceReference1.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetTeamsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeams", ReplyAction="*")]
        BetWeb.ServiceReference1.GetTeamsResponse GetTeams(BetWeb.ServiceReference1.GetTeamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeams", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamsResponse> GetTeamsAsync(BetWeb.ServiceReference1.GetTeamsRequest request);
        
        // CODEGEN: Generating message contract since element name GetBetsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBets", ReplyAction="*")]
        BetWeb.ServiceReference1.GetBetsResponse GetBets(BetWeb.ServiceReference1.GetBetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBets", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetBetsResponse> GetBetsAsync(BetWeb.ServiceReference1.GetBetsRequest request);
        
        // CODEGEN: Generating message contract since element name GetMatchesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatches", ReplyAction="*")]
        BetWeb.ServiceReference1.GetMatchesResponse GetMatches(BetWeb.ServiceReference1.GetMatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatches", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesResponse> GetMatchesAsync(BetWeb.ServiceReference1.GetMatchesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMatchesByLeagueResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchesByLeague", ReplyAction="*")]
        BetWeb.ServiceReference1.GetMatchesByLeagueResponse GetMatchesByLeague(BetWeb.ServiceReference1.GetMatchesByLeagueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchesByLeague", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesByLeagueResponse> GetMatchesByLeagueAsync(BetWeb.ServiceReference1.GetMatchesByLeagueRequest request);
        
        // CODEGEN: Generating message contract since element name GetLeaguesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeagues", ReplyAction="*")]
        BetWeb.ServiceReference1.GetLeaguesResponse GetLeagues(BetWeb.ServiceReference1.GetLeaguesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeagues", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetLeaguesResponse> GetLeaguesAsync(BetWeb.ServiceReference1.GetLeaguesRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserMoney", ReplyAction="*")]
        BetWeb.ServiceReference1.GetUserMoneyResponse GetUserMoney(BetWeb.ServiceReference1.GetUserMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserMoneyResponse> GetUserMoneyAsync(BetWeb.ServiceReference1.GetUserMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserMoney", ReplyAction="*")]
        BetWeb.ServiceReference1.SetUserMoneyResponse SetUserMoney(BetWeb.ServiceReference1.SetUserMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.SetUserMoneyResponse> SetUserMoneyAsync(BetWeb.ServiceReference1.SetUserMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUserMoney", ReplyAction="*")]
        BetWeb.ServiceReference1.SendUserMoneyResponse SendUserMoney(BetWeb.ServiceReference1.SendUserMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUserMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.SendUserMoneyResponse> SendUserMoneyAsync(BetWeb.ServiceReference1.SendUserMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBets", ReplyAction="*")]
        BetWeb.ServiceReference1.GetUserBetsResponse GetUserBets(BetWeb.ServiceReference1.GetUserBetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBets", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsResponse> GetUserBetsAsync(BetWeb.ServiceReference1.GetUserBetsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBetsByStatus", ReplyAction="*")]
        BetWeb.ServiceReference1.GetUserBetsByStatusResponse GetUserBetsByStatus(BetWeb.ServiceReference1.GetUserBetsByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBetsByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsByStatusResponse> GetUserBetsByStatusAsync(BetWeb.ServiceReference1.GetUserBetsByStatusRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBetForUser", ReplyAction="*")]
        BetWeb.ServiceReference1.AddBetForUserResponse AddBetForUser(BetWeb.ServiceReference1.AddBetForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBetForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddBetForUserResponse> AddBetForUserAsync(BetWeb.ServiceReference1.AddBetForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMatchMinute", ReplyAction="*")]
        void UpdateMatchMinute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMatchMinute", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateMatchMinuteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBetStatus", ReplyAction="*")]
        void UpdateBetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateBetStatusAsync();
        
        // CODEGEN: Generating message contract since element name GetTeamByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeamById", ReplyAction="*")]
        BetWeb.ServiceReference1.GetTeamByIdResponse GetTeamById(BetWeb.ServiceReference1.GetTeamByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeamById", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamByIdResponse> GetTeamByIdAsync(BetWeb.ServiceReference1.GetTeamByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetMatcheByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatcheById", ReplyAction="*")]
        BetWeb.ServiceReference1.GetMatcheByIdResponse GetMatcheById(BetWeb.ServiceReference1.GetMatcheByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatcheById", ReplyAction="*")]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatcheByIdResponse> GetMatcheByIdAsync(BetWeb.ServiceReference1.GetMatcheByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMatch", ReplyAction="*")]
        bool AddMatch(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMatch", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddMatchAsync(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(BetWeb.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haslo;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string login, string haslo) {
            this.login = login;
            this.haslo = haslo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(BetWeb.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUser", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.AddNewUserRequestBody Body;
        
        public AddNewUserRequest() {
        }
        
        public AddNewUserRequest(BetWeb.ServiceReference1.AddNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haslo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int wiek;
        
        public AddNewUserRequestBody() {
        }
        
        public AddNewUserRequestBody(string login, string haslo, int wiek) {
            this.login = login;
            this.haslo = haslo;
            this.wiek = wiek;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.AddNewUserResponseBody Body;
        
        public AddNewUserResponse() {
        }
        
        public AddNewUserResponse(BetWeb.ServiceReference1.AddNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNewUserResult;
        
        public AddNewUserResponseBody() {
        }
        
        public AddNewUserResponseBody(bool AddNewUserResult) {
            this.AddNewUserResult = AddNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(BetWeb.ServiceReference1.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(BetWeb.ServiceReference1.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(bool DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(BetWeb.ServiceReference1.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(BetWeb.ServiceReference1.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(string GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeams", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetTeamsRequestBody Body;
        
        public GetTeamsRequest() {
        }
        
        public GetTeamsRequest(BetWeb.ServiceReference1.GetTeamsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTeamsRequestBody {
        
        public GetTeamsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetTeamsResponseBody Body;
        
        public GetTeamsResponse() {
        }
        
        public GetTeamsResponse(BetWeb.ServiceReference1.GetTeamsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeamsResult;
        
        public GetTeamsResponseBody() {
        }
        
        public GetTeamsResponseBody(string GetTeamsResult) {
            this.GetTeamsResult = GetTeamsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBets", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetBetsRequestBody Body;
        
        public GetBetsRequest() {
        }
        
        public GetBetsRequest(BetWeb.ServiceReference1.GetBetsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBetsRequestBody {
        
        public GetBetsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBetsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetBetsResponseBody Body;
        
        public GetBetsResponse() {
        }
        
        public GetBetsResponse(BetWeb.ServiceReference1.GetBetsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBetsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBetsResult;
        
        public GetBetsResponseBody() {
        }
        
        public GetBetsResponseBody(string GetBetsResult) {
            this.GetBetsResult = GetBetsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatches", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatchesRequestBody Body;
        
        public GetMatchesRequest() {
        }
        
        public GetMatchesRequest(BetWeb.ServiceReference1.GetMatchesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMatchesRequestBody {
        
        public GetMatchesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatchesResponseBody Body;
        
        public GetMatchesResponse() {
        }
        
        public GetMatchesResponse(BetWeb.ServiceReference1.GetMatchesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMatchesResult;
        
        public GetMatchesResponseBody() {
        }
        
        public GetMatchesResponseBody(string GetMatchesResult) {
            this.GetMatchesResult = GetMatchesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesByLeagueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesByLeague", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatchesByLeagueRequestBody Body;
        
        public GetMatchesByLeagueRequest() {
        }
        
        public GetMatchesByLeagueRequest(BetWeb.ServiceReference1.GetMatchesByLeagueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesByLeagueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int leagueID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int time;
        
        public GetMatchesByLeagueRequestBody() {
        }
        
        public GetMatchesByLeagueRequestBody(int leagueID, int time) {
            this.leagueID = leagueID;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesByLeagueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesByLeagueResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatchesByLeagueResponseBody Body;
        
        public GetMatchesByLeagueResponse() {
        }
        
        public GetMatchesByLeagueResponse(BetWeb.ServiceReference1.GetMatchesByLeagueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesByLeagueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMatchesByLeagueResult;
        
        public GetMatchesByLeagueResponseBody() {
        }
        
        public GetMatchesByLeagueResponseBody(string GetMatchesByLeagueResult) {
            this.GetMatchesByLeagueResult = GetMatchesByLeagueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLeaguesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLeagues", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetLeaguesRequestBody Body;
        
        public GetLeaguesRequest() {
        }
        
        public GetLeaguesRequest(BetWeb.ServiceReference1.GetLeaguesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLeaguesRequestBody {
        
        public GetLeaguesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLeaguesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLeaguesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetLeaguesResponseBody Body;
        
        public GetLeaguesResponse() {
        }
        
        public GetLeaguesResponse(BetWeb.ServiceReference1.GetLeaguesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLeaguesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLeaguesResult;
        
        public GetLeaguesResponseBody() {
        }
        
        public GetLeaguesResponseBody(string GetLeaguesResult) {
            this.GetLeaguesResult = GetLeaguesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserMoney", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserMoneyRequestBody Body;
        
        public GetUserMoneyRequest() {
        }
        
        public GetUserMoneyRequest(BetWeb.ServiceReference1.GetUserMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetUserMoneyRequestBody() {
        }
        
        public GetUserMoneyRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserMoneyResponseBody Body;
        
        public GetUserMoneyResponse() {
        }
        
        public GetUserMoneyResponse(BetWeb.ServiceReference1.GetUserMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserMoneyResult;
        
        public GetUserMoneyResponseBody() {
        }
        
        public GetUserMoneyResponseBody(string GetUserMoneyResult) {
            this.GetUserMoneyResult = GetUserMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserMoney", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.SetUserMoneyRequestBody Body;
        
        public SetUserMoneyRequest() {
        }
        
        public SetUserMoneyRequest(BetWeb.ServiceReference1.SetUserMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int money;
        
        public SetUserMoneyRequestBody() {
        }
        
        public SetUserMoneyRequestBody(string login, int money) {
            this.login = login;
            this.money = money;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.SetUserMoneyResponseBody Body;
        
        public SetUserMoneyResponse() {
        }
        
        public SetUserMoneyResponse(BetWeb.ServiceReference1.SetUserMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetUserMoneyResponseBody {
        
        public SetUserMoneyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUserMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUserMoney", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.SendUserMoneyRequestBody Body;
        
        public SendUserMoneyRequest() {
        }
        
        public SendUserMoneyRequest(BetWeb.ServiceReference1.SendUserMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendUserMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int money;
        
        public SendUserMoneyRequestBody() {
        }
        
        public SendUserMoneyRequestBody(string login, int money) {
            this.login = login;
            this.money = money;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUserMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUserMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.SendUserMoneyResponseBody Body;
        
        public SendUserMoneyResponse() {
        }
        
        public SendUserMoneyResponse(BetWeb.ServiceReference1.SendUserMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendUserMoneyResponseBody {
        
        public SendUserMoneyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBets", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserBetsRequestBody Body;
        
        public GetUserBetsRequest() {
        }
        
        public GetUserBetsRequest(BetWeb.ServiceReference1.GetUserBetsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBetsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetUserBetsRequestBody() {
        }
        
        public GetUserBetsRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBetsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserBetsResponseBody Body;
        
        public GetUserBetsResponse() {
        }
        
        public GetUserBetsResponse(BetWeb.ServiceReference1.GetUserBetsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBetsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserBetsResult;
        
        public GetUserBetsResponseBody() {
        }
        
        public GetUserBetsResponseBody(string GetUserBetsResult) {
            this.GetUserBetsResult = GetUserBetsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBetsByStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBetsByStatus", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserBetsByStatusRequestBody Body;
        
        public GetUserBetsByStatusRequest() {
        }
        
        public GetUserBetsByStatusRequest(BetWeb.ServiceReference1.GetUserBetsByStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBetsByStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public GetUserBetsByStatusRequestBody() {
        }
        
        public GetUserBetsByStatusRequestBody(string login, string status) {
            this.login = login;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBetsByStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBetsByStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetUserBetsByStatusResponseBody Body;
        
        public GetUserBetsByStatusResponse() {
        }
        
        public GetUserBetsByStatusResponse(BetWeb.ServiceReference1.GetUserBetsByStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBetsByStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserBetsByStatusResult;
        
        public GetUserBetsByStatusResponseBody() {
        }
        
        public GetUserBetsByStatusResponseBody(string GetUserBetsByStatusResult) {
            this.GetUserBetsByStatusResult = GetUserBetsByStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBetForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBetForUser", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.AddBetForUserRequestBody Body;
        
        public AddBetForUserRequest() {
        }
        
        public AddBetForUserRequest(BetWeb.ServiceReference1.AddBetForUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBetForUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int money;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int matchid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int typ;
        
        public AddBetForUserRequestBody() {
        }
        
        public AddBetForUserRequestBody(string login, int money, int matchid, int typ) {
            this.login = login;
            this.money = money;
            this.matchid = matchid;
            this.typ = typ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBetForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBetForUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.AddBetForUserResponseBody Body;
        
        public AddBetForUserResponse() {
        }
        
        public AddBetForUserResponse(BetWeb.ServiceReference1.AddBetForUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBetForUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBetForUserResult;
        
        public AddBetForUserResponseBody() {
        }
        
        public AddBetForUserResponseBody(bool AddBetForUserResult) {
            this.AddBetForUserResult = AddBetForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamById", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetTeamByIdRequestBody Body;
        
        public GetTeamByIdRequest() {
        }
        
        public GetTeamByIdRequest(BetWeb.ServiceReference1.GetTeamByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int teamid;
        
        public GetTeamByIdRequestBody() {
        }
        
        public GetTeamByIdRequestBody(int teamid) {
            this.teamid = teamid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetTeamByIdResponseBody Body;
        
        public GetTeamByIdResponse() {
        }
        
        public GetTeamByIdResponse(BetWeb.ServiceReference1.GetTeamByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeamByIdResult;
        
        public GetTeamByIdResponseBody() {
        }
        
        public GetTeamByIdResponseBody(string GetTeamByIdResult) {
            this.GetTeamByIdResult = GetTeamByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatcheByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatcheById", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatcheByIdRequestBody Body;
        
        public GetMatcheByIdRequest() {
        }
        
        public GetMatcheByIdRequest(BetWeb.ServiceReference1.GetMatcheByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatcheByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int matchid;
        
        public GetMatcheByIdRequestBody() {
        }
        
        public GetMatcheByIdRequestBody(int matchid) {
            this.matchid = matchid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatcheByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatcheByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BetWeb.ServiceReference1.GetMatcheByIdResponseBody Body;
        
        public GetMatcheByIdResponse() {
        }
        
        public GetMatcheByIdResponse(BetWeb.ServiceReference1.GetMatcheByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatcheByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMatcheByIdResult;
        
        public GetMatcheByIdResponseBody() {
        }
        
        public GetMatcheByIdResponseBody(string GetMatcheByIdResult) {
            this.GetMatcheByIdResult = GetMatcheByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSToDatabaseSoapChannel : BetWeb.ServiceReference1.WSToDatabaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSToDatabaseSoapClient : System.ServiceModel.ClientBase<BetWeb.ServiceReference1.WSToDatabaseSoap>, BetWeb.ServiceReference1.WSToDatabaseSoap {
        
        public WSToDatabaseSoapClient() {
        }
        
        public WSToDatabaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSToDatabaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSToDatabaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSToDatabaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.LoginResponse BetWeb.ServiceReference1.WSToDatabaseSoap.Login(BetWeb.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string login1, string haslo) {
            BetWeb.ServiceReference1.LoginRequest inValue = new BetWeb.ServiceReference1.LoginRequest();
            inValue.Body = new BetWeb.ServiceReference1.LoginRequestBody();
            inValue.Body.login = login1;
            inValue.Body.haslo = haslo;
            BetWeb.ServiceReference1.LoginResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.LoginResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.LoginAsync(BetWeb.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.LoginResponse> LoginAsync(string login, string haslo) {
            BetWeb.ServiceReference1.LoginRequest inValue = new BetWeb.ServiceReference1.LoginRequest();
            inValue.Body = new BetWeb.ServiceReference1.LoginRequestBody();
            inValue.Body.login = login;
            inValue.Body.haslo = haslo;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.AddNewUserResponse BetWeb.ServiceReference1.WSToDatabaseSoap.AddNewUser(BetWeb.ServiceReference1.AddNewUserRequest request) {
            return base.Channel.AddNewUser(request);
        }
        
        public bool AddNewUser(string login, string haslo, int wiek) {
            BetWeb.ServiceReference1.AddNewUserRequest inValue = new BetWeb.ServiceReference1.AddNewUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.AddNewUserRequestBody();
            inValue.Body.login = login;
            inValue.Body.haslo = haslo;
            inValue.Body.wiek = wiek;
            BetWeb.ServiceReference1.AddNewUserResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).AddNewUser(inValue);
            return retVal.Body.AddNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddNewUserResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.AddNewUserAsync(BetWeb.ServiceReference1.AddNewUserRequest request) {
            return base.Channel.AddNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddNewUserResponse> AddNewUserAsync(string login, string haslo, int wiek) {
            BetWeb.ServiceReference1.AddNewUserRequest inValue = new BetWeb.ServiceReference1.AddNewUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.AddNewUserRequestBody();
            inValue.Body.login = login;
            inValue.Body.haslo = haslo;
            inValue.Body.wiek = wiek;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).AddNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.DeleteUserResponse BetWeb.ServiceReference1.WSToDatabaseSoap.DeleteUser(BetWeb.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public bool DeleteUser(string login) {
            BetWeb.ServiceReference1.DeleteUserRequest inValue = new BetWeb.ServiceReference1.DeleteUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.login = login;
            BetWeb.ServiceReference1.DeleteUserResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.DeleteUserResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.DeleteUserAsync(BetWeb.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.DeleteUserResponse> DeleteUserAsync(string login) {
            BetWeb.ServiceReference1.DeleteUserRequest inValue = new BetWeb.ServiceReference1.DeleteUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.login = login;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetUsersResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetUsers(BetWeb.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public string GetUsers() {
            BetWeb.ServiceReference1.GetUsersRequest inValue = new BetWeb.ServiceReference1.GetUsersRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUsersRequestBody();
            BetWeb.ServiceReference1.GetUsersResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUsersResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetUsersAsync(BetWeb.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUsersResponse> GetUsersAsync() {
            BetWeb.ServiceReference1.GetUsersRequest inValue = new BetWeb.ServiceReference1.GetUsersRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUsersRequestBody();
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetTeamsResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetTeams(BetWeb.ServiceReference1.GetTeamsRequest request) {
            return base.Channel.GetTeams(request);
        }
        
        public string GetTeams() {
            BetWeb.ServiceReference1.GetTeamsRequest inValue = new BetWeb.ServiceReference1.GetTeamsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetTeamsRequestBody();
            BetWeb.ServiceReference1.GetTeamsResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetTeams(inValue);
            return retVal.Body.GetTeamsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamsResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetTeamsAsync(BetWeb.ServiceReference1.GetTeamsRequest request) {
            return base.Channel.GetTeamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamsResponse> GetTeamsAsync() {
            BetWeb.ServiceReference1.GetTeamsRequest inValue = new BetWeb.ServiceReference1.GetTeamsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetTeamsRequestBody();
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetTeamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetBetsResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetBets(BetWeb.ServiceReference1.GetBetsRequest request) {
            return base.Channel.GetBets(request);
        }
        
        public string GetBets() {
            BetWeb.ServiceReference1.GetBetsRequest inValue = new BetWeb.ServiceReference1.GetBetsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetBetsRequestBody();
            BetWeb.ServiceReference1.GetBetsResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetBets(inValue);
            return retVal.Body.GetBetsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetBetsResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetBetsAsync(BetWeb.ServiceReference1.GetBetsRequest request) {
            return base.Channel.GetBetsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetBetsResponse> GetBetsAsync() {
            BetWeb.ServiceReference1.GetBetsRequest inValue = new BetWeb.ServiceReference1.GetBetsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetBetsRequestBody();
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetBetsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetMatchesResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatches(BetWeb.ServiceReference1.GetMatchesRequest request) {
            return base.Channel.GetMatches(request);
        }
        
        public string GetMatches() {
            BetWeb.ServiceReference1.GetMatchesRequest inValue = new BetWeb.ServiceReference1.GetMatchesRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatchesRequestBody();
            BetWeb.ServiceReference1.GetMatchesResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatches(inValue);
            return retVal.Body.GetMatchesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatchesAsync(BetWeb.ServiceReference1.GetMatchesRequest request) {
            return base.Channel.GetMatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesResponse> GetMatchesAsync() {
            BetWeb.ServiceReference1.GetMatchesRequest inValue = new BetWeb.ServiceReference1.GetMatchesRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatchesRequestBody();
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatchesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetMatchesByLeagueResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatchesByLeague(BetWeb.ServiceReference1.GetMatchesByLeagueRequest request) {
            return base.Channel.GetMatchesByLeague(request);
        }
        
        public string GetMatchesByLeague(int leagueID, int time) {
            BetWeb.ServiceReference1.GetMatchesByLeagueRequest inValue = new BetWeb.ServiceReference1.GetMatchesByLeagueRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatchesByLeagueRequestBody();
            inValue.Body.leagueID = leagueID;
            inValue.Body.time = time;
            BetWeb.ServiceReference1.GetMatchesByLeagueResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatchesByLeague(inValue);
            return retVal.Body.GetMatchesByLeagueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesByLeagueResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatchesByLeagueAsync(BetWeb.ServiceReference1.GetMatchesByLeagueRequest request) {
            return base.Channel.GetMatchesByLeagueAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatchesByLeagueResponse> GetMatchesByLeagueAsync(int leagueID, int time) {
            BetWeb.ServiceReference1.GetMatchesByLeagueRequest inValue = new BetWeb.ServiceReference1.GetMatchesByLeagueRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatchesByLeagueRequestBody();
            inValue.Body.leagueID = leagueID;
            inValue.Body.time = time;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatchesByLeagueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetLeaguesResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetLeagues(BetWeb.ServiceReference1.GetLeaguesRequest request) {
            return base.Channel.GetLeagues(request);
        }
        
        public string GetLeagues() {
            BetWeb.ServiceReference1.GetLeaguesRequest inValue = new BetWeb.ServiceReference1.GetLeaguesRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetLeaguesRequestBody();
            BetWeb.ServiceReference1.GetLeaguesResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetLeagues(inValue);
            return retVal.Body.GetLeaguesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetLeaguesResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetLeaguesAsync(BetWeb.ServiceReference1.GetLeaguesRequest request) {
            return base.Channel.GetLeaguesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetLeaguesResponse> GetLeaguesAsync() {
            BetWeb.ServiceReference1.GetLeaguesRequest inValue = new BetWeb.ServiceReference1.GetLeaguesRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetLeaguesRequestBody();
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetLeaguesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetUserMoneyResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserMoney(BetWeb.ServiceReference1.GetUserMoneyRequest request) {
            return base.Channel.GetUserMoney(request);
        }
        
        public string GetUserMoney(string login) {
            BetWeb.ServiceReference1.GetUserMoneyRequest inValue = new BetWeb.ServiceReference1.GetUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserMoneyRequestBody();
            inValue.Body.login = login;
            BetWeb.ServiceReference1.GetUserMoneyResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserMoney(inValue);
            return retVal.Body.GetUserMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserMoneyResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserMoneyAsync(BetWeb.ServiceReference1.GetUserMoneyRequest request) {
            return base.Channel.GetUserMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserMoneyResponse> GetUserMoneyAsync(string login) {
            BetWeb.ServiceReference1.GetUserMoneyRequest inValue = new BetWeb.ServiceReference1.GetUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserMoneyRequestBody();
            inValue.Body.login = login;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.SetUserMoneyResponse BetWeb.ServiceReference1.WSToDatabaseSoap.SetUserMoney(BetWeb.ServiceReference1.SetUserMoneyRequest request) {
            return base.Channel.SetUserMoney(request);
        }
        
        public void SetUserMoney(string login, int money) {
            BetWeb.ServiceReference1.SetUserMoneyRequest inValue = new BetWeb.ServiceReference1.SetUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.SetUserMoneyRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            BetWeb.ServiceReference1.SetUserMoneyResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).SetUserMoney(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.SetUserMoneyResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.SetUserMoneyAsync(BetWeb.ServiceReference1.SetUserMoneyRequest request) {
            return base.Channel.SetUserMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.SetUserMoneyResponse> SetUserMoneyAsync(string login, int money) {
            BetWeb.ServiceReference1.SetUserMoneyRequest inValue = new BetWeb.ServiceReference1.SetUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.SetUserMoneyRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).SetUserMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.SendUserMoneyResponse BetWeb.ServiceReference1.WSToDatabaseSoap.SendUserMoney(BetWeb.ServiceReference1.SendUserMoneyRequest request) {
            return base.Channel.SendUserMoney(request);
        }
        
        public void SendUserMoney(string login, int money) {
            BetWeb.ServiceReference1.SendUserMoneyRequest inValue = new BetWeb.ServiceReference1.SendUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.SendUserMoneyRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            BetWeb.ServiceReference1.SendUserMoneyResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).SendUserMoney(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.SendUserMoneyResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.SendUserMoneyAsync(BetWeb.ServiceReference1.SendUserMoneyRequest request) {
            return base.Channel.SendUserMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.SendUserMoneyResponse> SendUserMoneyAsync(string login, int money) {
            BetWeb.ServiceReference1.SendUserMoneyRequest inValue = new BetWeb.ServiceReference1.SendUserMoneyRequest();
            inValue.Body = new BetWeb.ServiceReference1.SendUserMoneyRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).SendUserMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetUserBetsResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserBets(BetWeb.ServiceReference1.GetUserBetsRequest request) {
            return base.Channel.GetUserBets(request);
        }
        
        public string GetUserBets(string login) {
            BetWeb.ServiceReference1.GetUserBetsRequest inValue = new BetWeb.ServiceReference1.GetUserBetsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserBetsRequestBody();
            inValue.Body.login = login;
            BetWeb.ServiceReference1.GetUserBetsResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserBets(inValue);
            return retVal.Body.GetUserBetsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserBetsAsync(BetWeb.ServiceReference1.GetUserBetsRequest request) {
            return base.Channel.GetUserBetsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsResponse> GetUserBetsAsync(string login) {
            BetWeb.ServiceReference1.GetUserBetsRequest inValue = new BetWeb.ServiceReference1.GetUserBetsRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserBetsRequestBody();
            inValue.Body.login = login;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserBetsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetUserBetsByStatusResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserBetsByStatus(BetWeb.ServiceReference1.GetUserBetsByStatusRequest request) {
            return base.Channel.GetUserBetsByStatus(request);
        }
        
        public string GetUserBetsByStatus(string login, string status) {
            BetWeb.ServiceReference1.GetUserBetsByStatusRequest inValue = new BetWeb.ServiceReference1.GetUserBetsByStatusRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserBetsByStatusRequestBody();
            inValue.Body.login = login;
            inValue.Body.status = status;
            BetWeb.ServiceReference1.GetUserBetsByStatusResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserBetsByStatus(inValue);
            return retVal.Body.GetUserBetsByStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsByStatusResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetUserBetsByStatusAsync(BetWeb.ServiceReference1.GetUserBetsByStatusRequest request) {
            return base.Channel.GetUserBetsByStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetUserBetsByStatusResponse> GetUserBetsByStatusAsync(string login, string status) {
            BetWeb.ServiceReference1.GetUserBetsByStatusRequest inValue = new BetWeb.ServiceReference1.GetUserBetsByStatusRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetUserBetsByStatusRequestBody();
            inValue.Body.login = login;
            inValue.Body.status = status;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetUserBetsByStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.AddBetForUserResponse BetWeb.ServiceReference1.WSToDatabaseSoap.AddBetForUser(BetWeb.ServiceReference1.AddBetForUserRequest request) {
            return base.Channel.AddBetForUser(request);
        }
        
        public bool AddBetForUser(string login, int money, int matchid, int typ) {
            BetWeb.ServiceReference1.AddBetForUserRequest inValue = new BetWeb.ServiceReference1.AddBetForUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.AddBetForUserRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            inValue.Body.matchid = matchid;
            inValue.Body.typ = typ;
            BetWeb.ServiceReference1.AddBetForUserResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).AddBetForUser(inValue);
            return retVal.Body.AddBetForUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddBetForUserResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.AddBetForUserAsync(BetWeb.ServiceReference1.AddBetForUserRequest request) {
            return base.Channel.AddBetForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.AddBetForUserResponse> AddBetForUserAsync(string login, int money, int matchid, int typ) {
            BetWeb.ServiceReference1.AddBetForUserRequest inValue = new BetWeb.ServiceReference1.AddBetForUserRequest();
            inValue.Body = new BetWeb.ServiceReference1.AddBetForUserRequestBody();
            inValue.Body.login = login;
            inValue.Body.money = money;
            inValue.Body.matchid = matchid;
            inValue.Body.typ = typ;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).AddBetForUserAsync(inValue);
        }
        
        public void UpdateMatchMinute() {
            base.Channel.UpdateMatchMinute();
        }
        
        public System.Threading.Tasks.Task UpdateMatchMinuteAsync() {
            return base.Channel.UpdateMatchMinuteAsync();
        }
        
        public void UpdateBetStatus() {
            base.Channel.UpdateBetStatus();
        }
        
        public System.Threading.Tasks.Task UpdateBetStatusAsync() {
            return base.Channel.UpdateBetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetTeamByIdResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetTeamById(BetWeb.ServiceReference1.GetTeamByIdRequest request) {
            return base.Channel.GetTeamById(request);
        }
        
        public string GetTeamById(int teamid) {
            BetWeb.ServiceReference1.GetTeamByIdRequest inValue = new BetWeb.ServiceReference1.GetTeamByIdRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetTeamByIdRequestBody();
            inValue.Body.teamid = teamid;
            BetWeb.ServiceReference1.GetTeamByIdResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetTeamById(inValue);
            return retVal.Body.GetTeamByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamByIdResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetTeamByIdAsync(BetWeb.ServiceReference1.GetTeamByIdRequest request) {
            return base.Channel.GetTeamByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetTeamByIdResponse> GetTeamByIdAsync(int teamid) {
            BetWeb.ServiceReference1.GetTeamByIdRequest inValue = new BetWeb.ServiceReference1.GetTeamByIdRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetTeamByIdRequestBody();
            inValue.Body.teamid = teamid;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetTeamByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BetWeb.ServiceReference1.GetMatcheByIdResponse BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatcheById(BetWeb.ServiceReference1.GetMatcheByIdRequest request) {
            return base.Channel.GetMatcheById(request);
        }
        
        public string GetMatcheById(int matchid) {
            BetWeb.ServiceReference1.GetMatcheByIdRequest inValue = new BetWeb.ServiceReference1.GetMatcheByIdRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatcheByIdRequestBody();
            inValue.Body.matchid = matchid;
            BetWeb.ServiceReference1.GetMatcheByIdResponse retVal = ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatcheById(inValue);
            return retVal.Body.GetMatcheByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatcheByIdResponse> BetWeb.ServiceReference1.WSToDatabaseSoap.GetMatcheByIdAsync(BetWeb.ServiceReference1.GetMatcheByIdRequest request) {
            return base.Channel.GetMatcheByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BetWeb.ServiceReference1.GetMatcheByIdResponse> GetMatcheByIdAsync(int matchid) {
            BetWeb.ServiceReference1.GetMatcheByIdRequest inValue = new BetWeb.ServiceReference1.GetMatcheByIdRequest();
            inValue.Body = new BetWeb.ServiceReference1.GetMatcheByIdRequestBody();
            inValue.Body.matchid = matchid;
            return ((BetWeb.ServiceReference1.WSToDatabaseSoap)(this)).GetMatcheByIdAsync(inValue);
        }
        
        public bool AddMatch(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta) {
            return base.Channel.AddMatch(kurs, id_gosc, id_gosp, data, bramki_gosc, bramki_gosp, minuta);
        }
        
        public System.Threading.Tasks.Task<bool> AddMatchAsync(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta) {
            return base.Channel.AddMatchAsync(kurs, id_gosc, id_gosp, data, bramki_gosc, bramki_gosp, minuta);
        }
    }
}
