//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attrib
    {
        public int id_przyp { get; set; }
        public Nullable<int> id_mecz { get; set; }
        public Nullable<int> id_zaklad { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Bet Bet { get; set; }
    }
}
