//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bet()
        {
            this.Attribs = new HashSet<Attrib>();
        }
    
        public int id_zaklad { get; set; }
        public int kwota { get; set; }
        public int wygrana { get; set; }
        public Nullable<int> id_mecz { get; set; }
        public Nullable<int> id_user { get; set; }
        public string status { get; set; }
        public Nullable<int> typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attrib> Attribs { get; set; }
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
