//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BetConsole.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSToDatabaseSoap", Namespace="http://tempuri.org/")]
    public partial class WSToDatabase : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchesByLeagueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaguesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUserMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserBetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserBetsByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBetForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMatchMinuteOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatcheByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGoalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMatchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSToDatabase() {
            this.Url = global::BetConsole.Properties.Settings.Default.BetConsole_localhost_WSToDatabase;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event AddNewUserCompletedEventHandler AddNewUserCompleted;
        
        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetTeamsCompletedEventHandler GetTeamsCompleted;
        
        /// <remarks/>
        public event GetBetsCompletedEventHandler GetBetsCompleted;
        
        /// <remarks/>
        public event GetMatchesCompletedEventHandler GetMatchesCompleted;
        
        /// <remarks/>
        public event GetMatchesByLeagueCompletedEventHandler GetMatchesByLeagueCompleted;
        
        /// <remarks/>
        public event GetLeaguesCompletedEventHandler GetLeaguesCompleted;
        
        /// <remarks/>
        public event GetUserMoneyCompletedEventHandler GetUserMoneyCompleted;
        
        /// <remarks/>
        public event SetUserMoneyCompletedEventHandler SetUserMoneyCompleted;
        
        /// <remarks/>
        public event SendUserMoneyCompletedEventHandler SendUserMoneyCompleted;
        
        /// <remarks/>
        public event GetUserBetsCompletedEventHandler GetUserBetsCompleted;
        
        /// <remarks/>
        public event GetUserBetsByStatusCompletedEventHandler GetUserBetsByStatusCompleted;
        
        /// <remarks/>
        public event AddBetForUserCompletedEventHandler AddBetForUserCompleted;
        
        /// <remarks/>
        public event UpdateMatchMinuteCompletedEventHandler UpdateMatchMinuteCompleted;
        
        /// <remarks/>
        public event UpdateBetStatusCompletedEventHandler UpdateBetStatusCompleted;
        
        /// <remarks/>
        public event GetTeamByIdCompletedEventHandler GetTeamByIdCompleted;
        
        /// <remarks/>
        public event GetMatcheByIdCompletedEventHandler GetMatcheByIdCompleted;
        
        /// <remarks/>
        public event AddGoalCompletedEventHandler AddGoalCompleted;
        
        /// <remarks/>
        public event AddMatchCompletedEventHandler AddMatchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login([System.Xml.Serialization.XmlElementAttribute("login")] string login1, string haslo) {
            object[] results = this.Invoke("Login", new object[] {
                        login1,
                        haslo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string login1, string haslo) {
            this.LoginAsync(login1, haslo, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string login1, string haslo, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        login1,
                        haslo}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddNewUser(string login, string haslo, int wiek) {
            object[] results = this.Invoke("AddNewUser", new object[] {
                        login,
                        haslo,
                        wiek});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewUserAsync(string login, string haslo, int wiek) {
            this.AddNewUserAsync(login, haslo, wiek, null);
        }
        
        /// <remarks/>
        public void AddNewUserAsync(string login, string haslo, int wiek, object userState) {
            if ((this.AddNewUserOperationCompleted == null)) {
                this.AddNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewUserOperationCompleted);
            }
            this.InvokeAsync("AddNewUser", new object[] {
                        login,
                        haslo,
                        wiek}, this.AddNewUserOperationCompleted, userState);
        }
        
        private void OnAddNewUserOperationCompleted(object arg) {
            if ((this.AddNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewUserCompleted(this, new AddNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUser(string login) {
            object[] results = this.Invoke("DeleteUser", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string login) {
            this.DeleteUserAsync(login, null);
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string login, object userState) {
            if ((this.DeleteUserOperationCompleted == null)) {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                        login}, this.DeleteUserOperationCompleted, userState);
        }
        
        private void OnDeleteUserOperationCompleted(object arg) {
            if ((this.DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new DeleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUsers() {
            object[] results = this.Invoke("GetUsers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync() {
            this.GetUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[0], this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTeams() {
            object[] results = this.Invoke("GetTeams", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamsAsync() {
            this.GetTeamsAsync(null);
        }
        
        /// <remarks/>
        public void GetTeamsAsync(object userState) {
            if ((this.GetTeamsOperationCompleted == null)) {
                this.GetTeamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamsOperationCompleted);
            }
            this.InvokeAsync("GetTeams", new object[0], this.GetTeamsOperationCompleted, userState);
        }
        
        private void OnGetTeamsOperationCompleted(object arg) {
            if ((this.GetTeamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamsCompleted(this, new GetTeamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBets() {
            object[] results = this.Invoke("GetBets", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBetsAsync() {
            this.GetBetsAsync(null);
        }
        
        /// <remarks/>
        public void GetBetsAsync(object userState) {
            if ((this.GetBetsOperationCompleted == null)) {
                this.GetBetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBetsOperationCompleted);
            }
            this.InvokeAsync("GetBets", new object[0], this.GetBetsOperationCompleted, userState);
        }
        
        private void OnGetBetsOperationCompleted(object arg) {
            if ((this.GetBetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBetsCompleted(this, new GetBetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMatches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMatches() {
            object[] results = this.Invoke("GetMatches", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchesAsync() {
            this.GetMatchesAsync(null);
        }
        
        /// <remarks/>
        public void GetMatchesAsync(object userState) {
            if ((this.GetMatchesOperationCompleted == null)) {
                this.GetMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchesOperationCompleted);
            }
            this.InvokeAsync("GetMatches", new object[0], this.GetMatchesOperationCompleted, userState);
        }
        
        private void OnGetMatchesOperationCompleted(object arg) {
            if ((this.GetMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchesCompleted(this, new GetMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMatchesByLeague", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMatchesByLeague(int leagueID, int time) {
            object[] results = this.Invoke("GetMatchesByLeague", new object[] {
                        leagueID,
                        time});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchesByLeagueAsync(int leagueID, int time) {
            this.GetMatchesByLeagueAsync(leagueID, time, null);
        }
        
        /// <remarks/>
        public void GetMatchesByLeagueAsync(int leagueID, int time, object userState) {
            if ((this.GetMatchesByLeagueOperationCompleted == null)) {
                this.GetMatchesByLeagueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchesByLeagueOperationCompleted);
            }
            this.InvokeAsync("GetMatchesByLeague", new object[] {
                        leagueID,
                        time}, this.GetMatchesByLeagueOperationCompleted, userState);
        }
        
        private void OnGetMatchesByLeagueOperationCompleted(object arg) {
            if ((this.GetMatchesByLeagueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchesByLeagueCompleted(this, new GetMatchesByLeagueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeagues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLeagues() {
            object[] results = this.Invoke("GetLeagues", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaguesAsync() {
            this.GetLeaguesAsync(null);
        }
        
        /// <remarks/>
        public void GetLeaguesAsync(object userState) {
            if ((this.GetLeaguesOperationCompleted == null)) {
                this.GetLeaguesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaguesOperationCompleted);
            }
            this.InvokeAsync("GetLeagues", new object[0], this.GetLeaguesOperationCompleted, userState);
        }
        
        private void OnGetLeaguesOperationCompleted(object arg) {
            if ((this.GetLeaguesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaguesCompleted(this, new GetLeaguesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserMoney(string login) {
            object[] results = this.Invoke("GetUserMoney", new object[] {
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserMoneyAsync(string login) {
            this.GetUserMoneyAsync(login, null);
        }
        
        /// <remarks/>
        public void GetUserMoneyAsync(string login, object userState) {
            if ((this.GetUserMoneyOperationCompleted == null)) {
                this.GetUserMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserMoneyOperationCompleted);
            }
            this.InvokeAsync("GetUserMoney", new object[] {
                        login}, this.GetUserMoneyOperationCompleted, userState);
        }
        
        private void OnGetUserMoneyOperationCompleted(object arg) {
            if ((this.GetUserMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserMoneyCompleted(this, new GetUserMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUserMoney(string login, int money) {
            this.Invoke("SetUserMoney", new object[] {
                        login,
                        money});
        }
        
        /// <remarks/>
        public void SetUserMoneyAsync(string login, int money) {
            this.SetUserMoneyAsync(login, money, null);
        }
        
        /// <remarks/>
        public void SetUserMoneyAsync(string login, int money, object userState) {
            if ((this.SetUserMoneyOperationCompleted == null)) {
                this.SetUserMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserMoneyOperationCompleted);
            }
            this.InvokeAsync("SetUserMoney", new object[] {
                        login,
                        money}, this.SetUserMoneyOperationCompleted, userState);
        }
        
        private void OnSetUserMoneyOperationCompleted(object arg) {
            if ((this.SetUserMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserMoneyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUserMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendUserMoney(string login, int money) {
            this.Invoke("SendUserMoney", new object[] {
                        login,
                        money});
        }
        
        /// <remarks/>
        public void SendUserMoneyAsync(string login, int money) {
            this.SendUserMoneyAsync(login, money, null);
        }
        
        /// <remarks/>
        public void SendUserMoneyAsync(string login, int money, object userState) {
            if ((this.SendUserMoneyOperationCompleted == null)) {
                this.SendUserMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUserMoneyOperationCompleted);
            }
            this.InvokeAsync("SendUserMoney", new object[] {
                        login,
                        money}, this.SendUserMoneyOperationCompleted, userState);
        }
        
        private void OnSendUserMoneyOperationCompleted(object arg) {
            if ((this.SendUserMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUserMoneyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserBets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserBets(string login) {
            object[] results = this.Invoke("GetUserBets", new object[] {
                        login});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserBetsAsync(string login) {
            this.GetUserBetsAsync(login, null);
        }
        
        /// <remarks/>
        public void GetUserBetsAsync(string login, object userState) {
            if ((this.GetUserBetsOperationCompleted == null)) {
                this.GetUserBetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserBetsOperationCompleted);
            }
            this.InvokeAsync("GetUserBets", new object[] {
                        login}, this.GetUserBetsOperationCompleted, userState);
        }
        
        private void OnGetUserBetsOperationCompleted(object arg) {
            if ((this.GetUserBetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserBetsCompleted(this, new GetUserBetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserBetsByStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserBetsByStatus(string login, string status) {
            object[] results = this.Invoke("GetUserBetsByStatus", new object[] {
                        login,
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserBetsByStatusAsync(string login, string status) {
            this.GetUserBetsByStatusAsync(login, status, null);
        }
        
        /// <remarks/>
        public void GetUserBetsByStatusAsync(string login, string status, object userState) {
            if ((this.GetUserBetsByStatusOperationCompleted == null)) {
                this.GetUserBetsByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserBetsByStatusOperationCompleted);
            }
            this.InvokeAsync("GetUserBetsByStatus", new object[] {
                        login,
                        status}, this.GetUserBetsByStatusOperationCompleted, userState);
        }
        
        private void OnGetUserBetsByStatusOperationCompleted(object arg) {
            if ((this.GetUserBetsByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserBetsByStatusCompleted(this, new GetUserBetsByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBetForUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddBetForUser(string login, int money, int matchid, int typ) {
            object[] results = this.Invoke("AddBetForUser", new object[] {
                        login,
                        money,
                        matchid,
                        typ});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddBetForUserAsync(string login, int money, int matchid, int typ) {
            this.AddBetForUserAsync(login, money, matchid, typ, null);
        }
        
        /// <remarks/>
        public void AddBetForUserAsync(string login, int money, int matchid, int typ, object userState) {
            if ((this.AddBetForUserOperationCompleted == null)) {
                this.AddBetForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBetForUserOperationCompleted);
            }
            this.InvokeAsync("AddBetForUser", new object[] {
                        login,
                        money,
                        matchid,
                        typ}, this.AddBetForUserOperationCompleted, userState);
        }
        
        private void OnAddBetForUserOperationCompleted(object arg) {
            if ((this.AddBetForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBetForUserCompleted(this, new AddBetForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMatchMinute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMatchMinute() {
            this.Invoke("UpdateMatchMinute", new object[0]);
        }
        
        /// <remarks/>
        public void UpdateMatchMinuteAsync() {
            this.UpdateMatchMinuteAsync(null);
        }
        
        /// <remarks/>
        public void UpdateMatchMinuteAsync(object userState) {
            if ((this.UpdateMatchMinuteOperationCompleted == null)) {
                this.UpdateMatchMinuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMatchMinuteOperationCompleted);
            }
            this.InvokeAsync("UpdateMatchMinute", new object[0], this.UpdateMatchMinuteOperationCompleted, userState);
        }
        
        private void OnUpdateMatchMinuteOperationCompleted(object arg) {
            if ((this.UpdateMatchMinuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMatchMinuteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBetStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateBetStatus() {
            this.Invoke("UpdateBetStatus", new object[0]);
        }
        
        /// <remarks/>
        public void UpdateBetStatusAsync() {
            this.UpdateBetStatusAsync(null);
        }
        
        /// <remarks/>
        public void UpdateBetStatusAsync(object userState) {
            if ((this.UpdateBetStatusOperationCompleted == null)) {
                this.UpdateBetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBetStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateBetStatus", new object[0], this.UpdateBetStatusOperationCompleted, userState);
        }
        
        private void OnUpdateBetStatusOperationCompleted(object arg) {
            if ((this.UpdateBetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBetStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeamById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTeamById(int teamid) {
            object[] results = this.Invoke("GetTeamById", new object[] {
                        teamid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamByIdAsync(int teamid) {
            this.GetTeamByIdAsync(teamid, null);
        }
        
        /// <remarks/>
        public void GetTeamByIdAsync(int teamid, object userState) {
            if ((this.GetTeamByIdOperationCompleted == null)) {
                this.GetTeamByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamByIdOperationCompleted);
            }
            this.InvokeAsync("GetTeamById", new object[] {
                        teamid}, this.GetTeamByIdOperationCompleted, userState);
        }
        
        private void OnGetTeamByIdOperationCompleted(object arg) {
            if ((this.GetTeamByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamByIdCompleted(this, new GetTeamByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMatcheById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMatcheById(int matchid) {
            object[] results = this.Invoke("GetMatcheById", new object[] {
                        matchid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatcheByIdAsync(int matchid) {
            this.GetMatcheByIdAsync(matchid, null);
        }
        
        /// <remarks/>
        public void GetMatcheByIdAsync(int matchid, object userState) {
            if ((this.GetMatcheByIdOperationCompleted == null)) {
                this.GetMatcheByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatcheByIdOperationCompleted);
            }
            this.InvokeAsync("GetMatcheById", new object[] {
                        matchid}, this.GetMatcheByIdOperationCompleted, userState);
        }
        
        private void OnGetMatcheByIdOperationCompleted(object arg) {
            if ((this.GetMatcheByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatcheByIdCompleted(this, new GetMatcheByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGoal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddGoal(int matchId, int czyGol) {
            this.Invoke("AddGoal", new object[] {
                        matchId,
                        czyGol});
        }
        
        /// <remarks/>
        public void AddGoalAsync(int matchId, int czyGol) {
            this.AddGoalAsync(matchId, czyGol, null);
        }
        
        /// <remarks/>
        public void AddGoalAsync(int matchId, int czyGol, object userState) {
            if ((this.AddGoalOperationCompleted == null)) {
                this.AddGoalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGoalOperationCompleted);
            }
            this.InvokeAsync("AddGoal", new object[] {
                        matchId,
                        czyGol}, this.AddGoalOperationCompleted, userState);
        }
        
        private void OnAddGoalOperationCompleted(object arg) {
            if ((this.AddGoalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGoalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMatch(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta) {
            object[] results = this.Invoke("AddMatch", new object[] {
                        kurs,
                        id_gosc,
                        id_gosp,
                        data,
                        bramki_gosc,
                        bramki_gosp,
                        minuta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMatchAsync(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta) {
            this.AddMatchAsync(kurs, id_gosc, id_gosp, data, bramki_gosc, bramki_gosp, minuta, null);
        }
        
        /// <remarks/>
        public void AddMatchAsync(int kurs, int id_gosc, int id_gosp, System.DateTime data, int bramki_gosc, int bramki_gosp, int minuta, object userState) {
            if ((this.AddMatchOperationCompleted == null)) {
                this.AddMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMatchOperationCompleted);
            }
            this.InvokeAsync("AddMatch", new object[] {
                        kurs,
                        id_gosc,
                        id_gosp,
                        data,
                        bramki_gosc,
                        bramki_gosp,
                        minuta}, this.AddMatchOperationCompleted, userState);
        }
        
        private void OnAddMatchOperationCompleted(object arg) {
            if ((this.AddMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMatchCompleted(this, new AddMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddNewUserCompletedEventHandler(object sender, AddNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteUserCompletedEventHandler(object sender, DeleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetTeamsCompletedEventHandler(object sender, GetTeamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetBetsCompletedEventHandler(object sender, GetBetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetMatchesCompletedEventHandler(object sender, GetMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetMatchesByLeagueCompletedEventHandler(object sender, GetMatchesByLeagueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchesByLeagueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchesByLeagueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetLeaguesCompletedEventHandler(object sender, GetLeaguesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaguesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaguesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUserMoneyCompletedEventHandler(object sender, GetUserMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetUserMoneyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SendUserMoneyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUserBetsCompletedEventHandler(object sender, GetUserBetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserBetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserBetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUserBetsByStatusCompletedEventHandler(object sender, GetUserBetsByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserBetsByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserBetsByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddBetForUserCompletedEventHandler(object sender, AddBetForUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBetForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBetForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateMatchMinuteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateBetStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetTeamByIdCompletedEventHandler(object sender, GetTeamByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetMatcheByIdCompletedEventHandler(object sender, GetMatcheByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatcheByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatcheByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddGoalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddMatchCompletedEventHandler(object sender, AddMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591